/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.vinni.result4dos.grafica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Vinni.
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("Jugando Jugando se va ganando  ..!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalir = new javax.swing.JButton();
        btRegistraPartido = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btGpartidos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btSalir.setText("SALIR");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(490, 260, 90, 30);

        btRegistraPartido.setText("REGISTRAR PARTIDO");
        btRegistraPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistraPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistraPartido);
        btRegistraPartido.setBounds(260, 140, 230, 30);

        jButton4.setText("VER RESULTADOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 180, 230, 30);

        jLabel6.setText("autor: Giovanni Briceño - vinni 2021 - vinni9@gmail.com");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 330, 290, 14);

        btGpartidos1.setText("GESTIONAR EQUIPOS");
        btGpartidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGpartidos1ActionPerformed(evt);
            }
        });
        getContentPane().add(btGpartidos1);
        btGpartidos1.setBounds(260, 100, 230, 30);

        setSize(new java.awt.Dimension(787, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btRegistraPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistraPartidoActionPerformed
        // TODO add your handling code here:
        this.cargarPartidos();
    }//GEN-LAST:event_btRegistraPartidoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.cargarResultados();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btGpartidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGpartidos1ActionPerformed
        // TODO add your handling code here:
        this.cargarEquipos();
    }//GEN-LAST:event_btGpartidos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {

            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGpartidos1;
    private javax.swing.JButton btRegistraPartido;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

 
    private void cargarGEquipos() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEquipos().setVisible(true);
            }
        });
    }
    private void cargarResultados() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaResultados().setVisible(true);
            }
        });
    }
    private void cargarPartidos() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPartidos().setVisible(true);
            }
        });
    }

    private void cargarEquipos() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEquipos().setVisible(true);
            }
        });    
    }
    
}
