/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.vinni.result4dos.grafica;

import co.vinni.result4dos.dao.OperacionesEquipo;
import co.vinni.result4dos.dao.OperacionesPartido;
import co.vinni.result4dos.dto.Equipo;
import co.vinni.result4dos.dto.Partido;
import co.vinni.result4dos.util.Utilidades;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinni
 */
public class VentanaPartidos extends javax.swing.JFrame {

    private JDateChooser fechaSel;
    private List<Partido> listadoPartidos;
    private Map<String, Equipo> listadoEquiposM = new HashMap<String, Equipo>();

    
    /**
     * Creates new form VentanaPartidos
     */
    public VentanaPartidos() {
        initComponents();
        cargarPartidos();
        cargarEquipos();
        fechaSel = new JDateChooser();
        fechaSel.setBounds(100, 30, 150, 20);
        
        this.pCrear.add(fechaSel);
        this.setTitle("A jugar ..!!");
        this.cjId.setVisible(false);
        pCrear.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pCrear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cjId = new javax.swing.JTextField();
        btEditar = new javax.swing.JButton();
        btCrear = new javax.swing.JButton();
        lTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cjGolL = new javax.swing.JTextField();
        cjGolV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cjElocal = new javax.swing.JComboBox<>();
        cjElVisita = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEquipos = new javax.swing.JTable();
        btBorrar = new javax.swing.JButton();
        btNuevoE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("<-- Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 310, 90, 23);

        pCrear.setBackground(new java.awt.Color(154, 168, 191));
        pCrear.setLayout(null);

        jLabel1.setText("Equipo Local");
        pCrear.add(jLabel1);
        jLabel1.setBounds(30, 60, 80, 14);

        jLabel2.setText("Equipo Visitante");
        pCrear.add(jLabel2);
        jLabel2.setBounds(190, 60, 120, 14);
        pCrear.add(cjId);
        cjId.setBounds(400, 30, 40, 20);

        btEditar.setText("Actualizar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        pCrear.add(btEditar);
        btEditar.setBounds(380, 60, 80, 23);

        btCrear.setText("Crear");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });
        pCrear.add(btCrear);
        btCrear.setBounds(380, 60, 80, 23);

        lTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lTitulo.setText("titulo");
        pCrear.add(lTitulo);
        lTitulo.setBounds(20, 10, 260, 15);

        jLabel4.setText("goles");
        pCrear.add(jLabel4);
        jLabel4.setBounds(310, 60, 34, 14);

        jLabel5.setText("goles");
        pCrear.add(jLabel5);
        jLabel5.setBounds(130, 60, 25, 14);
        pCrear.add(cjGolL);
        cjGolL.setBounds(120, 80, 40, 20);
        pCrear.add(cjGolV);
        cjGolV.setBounds(310, 80, 30, 20);

        jLabel6.setText("Fecha: ");
        pCrear.add(jLabel6);
        jLabel6.setBounds(25, 30, 60, 14);
        pCrear.add(cjElocal);
        cjElocal.setBounds(10, 80, 100, 20);
        pCrear.add(cjElVisita);
        cjElVisita.setBounds(190, 80, 100, 20);

        getContentPane().add(pCrear);
        pCrear.setBounds(30, 190, 470, 110);

        tbEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEquipos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 470, 110);

        btBorrar.setText("Borrar partido seleccionado");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btBorrar);
        btBorrar.setBounds(310, 150, 180, 23);

        btNuevoE.setText("Nuevo partido");
        btNuevoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoEActionPerformed(evt);
            }
        });
        getContentPane().add(btNuevoE);
        btNuevoE.setBounds(20, 150, 130, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LISTADO DE PARTIDOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 20, 190, 14);

        setSize(new java.awt.Dimension(595, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        this.editar();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        // TODO add your handling code here:
        this.crear();
    }//GEN-LAST:event_btCrearActionPerformed

    private void tbEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEquiposMouseClicked
        // TODO add your handling code here:
        this.cambiovalor();
    }//GEN-LAST:event_tbEquiposMouseClicked

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        // TODO add your handling code here:
        this.borrar();
    }//GEN-LAST:event_btBorrarActionPerformed

    private void btNuevoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoEActionPerformed
        // TODO add your handling code here:
        this.nuevoequipo();
    }//GEN-LAST:event_btNuevoEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        try {

            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPartidos().setVisible(true);
            }
        });
    }
    private void crear() {
        
        if (this.cjElocal.getSelectedIndex()<0 || this.cjElocal.getSelectedIndex()<0 || 
                this.fechaSel.getDate() == null || this.cjGolL.getText().isEmpty() || this.cjGolV.getText().isEmpty()){
            this.mensajeWarning("Algun valor requerido esta faltando. ¡Verifique!");
            return ;
        }
        if (((String)this.cjElocal.getSelectedItem()).equals(((String)this.cjElVisita.getSelectedItem()))){
            this.mensajeWarning("El equipo Local y visitante son iguales. ¡Verifique!");
            return ;
        }
        OperacionesPartido oper = new OperacionesPartido();
        Partido e = new Partido();
        e.setFecha(this.fechaSel.getDate());
        e.setEquipoLocal(this.listadoEquiposM.get((String)this.cjElocal.getSelectedItem()));
        e.setGolesLocal(Utilidades.convertirNumeroI(this.cjGolL.getText()));
        e.setEquipoVisitante(this.listadoEquiposM.get((String)this.cjElVisita.getSelectedItem()));
        e.setGolesVisitante(Utilidades.convertirNumeroI(this.cjGolV.getText()));

        int x = oper.crear(e);
        if (x >0){
            mensajeOK("Se creó el partido ");
            cargarPartidos();
            return ;
        }else{
            mensajeWarning("No se creó el partido, verifique e intente de nuevo. ");
        }
            
    }
    private void mensajeOK(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    private void mensajeWarning(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.WARNING_MESSAGE);
    }

    private void cargarEquipos() {
        OperacionesEquipo oper = new OperacionesEquipo();
        
        List<Equipo> listaE =  oper.consultarAll();
        for (int i = 0; i < listaE.size(); i++) {
            Equipo dato = listaE.get(i);
            listadoEquiposM.put(dato.getNombre(), dato);
            this.cjElocal.addItem(dato.getNombre());
            this.cjElVisita.addItem(dato.getNombre());
        }
        
        
        
        
    }

    private void editar() {
        int index = tbEquipos.getSelectedRow();
        OperacionesPartido oper = new OperacionesPartido();
        Partido e = new Partido();
        e.setId(Utilidades.convertirNumeroL(this.cjId.getText()));
        e.setGolesLocal(Utilidades.convertirNumeroI(this.cjGolL.getText()));
        e.setGolesVisitante(Utilidades.convertirNumeroI(this.cjGolV.getText()));
        
        int x = oper.editar(e);
        if (x >0){
            mensajeOK("Se cambio la información de goles del partido ");
            cargarPartidos();
            this.limpiar();
            return ;
        }else{
            mensajeWarning("No se actualizó la información del partido, verifique e intente de nuevo. ");
        }
    }
    private void borrar() {
        int indice = tbEquipos.getSelectedRow();
        if (indice < 0){
            this.mensajeWarning("Seleccione el partido que desea borrar. ");
            return ;
        }
        String[] optiones = {"Si", "No"};
        int rta = JOptionPane.showOptionDialog(null, "¿Desea borrar el equipo ?", "Información", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, optiones, optiones[1]);
         if (rta == 0) {
             
             String id = tbEquipos.getValueAt(indice, 0).toString();
             OperacionesPartido oper = new OperacionesPartido();
             Partido e = new Partido();
             e.setId(new Long(id));
             int rta1 = oper.borrar(e);
             if (rta1 > 0 ){
                 this.mensajeOK("Se borró el partido exitosamente.");
                 cargarPartidos();
             }else{
                 this.mensajeWarning("No se borró el partido. ¡Verifique!");
             }
             
         } 
        
    }

    private void cambiovalor() {
        this.lTitulo.setText("Modifique la información del partido. ");
        this.cjId.setText(tbEquipos.getValueAt(tbEquipos.getSelectedRow(), 0).toString());
        String fecha = tbEquipos.getValueAt(tbEquipos.getSelectedRow(), 1).toString();
        Date laFecha = Utilidades.obtenerFecha("dd/MM/yyyy", fecha);
        if (laFecha != null){
            fechaSel.setDate(laFecha);
        }
        String eqLocal = tbEquipos.getValueAt(tbEquipos.getSelectedRow(), 2).toString();
        this.cjElocal.setSelectedItem(eqLocal);
        this.cjGolL.setText(tbEquipos.getValueAt(tbEquipos.getSelectedRow(), 3).toString());
        String eqVisit = tbEquipos.getValueAt(tbEquipos.getSelectedRow(), 4).toString();
        this.cjElVisita.setSelectedItem(eqVisit);
        this.cjGolV.setText(tbEquipos.getValueAt(tbEquipos.getSelectedRow(), 5).toString());
        
        this.pCrear.setVisible(true);
        this.btEditar.setVisible(true);
        this.btCrear.setVisible(false);
        this.pCrear.setBackground(new Color(190, 190, 190));
        
    }

    private void nuevoequipo() {
        this.lTitulo.setText("Diligencie la información del nuevo partido. ");
        this.btCrear.setVisible(true);
        this.btEditar.setVisible(false);
        this.pCrear.setVisible(true);
        this.limpiar();
        this.pCrear.setBackground(new Color(154, 168, 191));
    }

    private void limpiar() {
        this.cjId.setText("");
        
        this.cjGolL.setText("");
        this.cjGolV.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btCrear;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btNuevoE;
    private javax.swing.JComboBox<String> cjElVisita;
    private javax.swing.JComboBox<String> cjElocal;
    private javax.swing.JTextField cjGolL;
    private javax.swing.JTextField cjGolV;
    private javax.swing.JTextField cjId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel pCrear;
    private javax.swing.JTable tbEquipos;
    // End of variables declaration//GEN-END:variables

    private void cargarPartidos() {
        OperacionesPartido oper = new OperacionesPartido();
        this.listadoPartidos = oper.consultarAll();
        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnas = {"ID", "FECHA", "LOCAL ", "GOL LOCAL","VISITANTE", "GOL VISITANTE"};

        modelo.setColumnIdentifiers(columnas);
        
        for (int i = 0; i < listadoPartidos.size(); i++) {
            Partido dato = listadoPartidos.get(i);
            Object [] fila = new Object[6];
            fila[0] = dato.getId();
            fila[1] = Utilidades.formatoFecha( dato.getFecha()) ;
            fila[2] = dato.getEquipoLocal().getNombre();
            fila[3] = dato.getGolesLocal();
            fila[4] = dato.getEquipoVisitante().getNombre();
            fila[5] = dato.getGolesVisitante();
             modelo.addRow(fila);
        }
        
        tbEquipos.setModel(modelo);    
    }
}
